config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'users#index'
  resources :resolutions  
  resources :articles
  resources :users do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :content, presence: true
  belongs_to :user

  def self.search(search)
    if search != ''
      Article.where('content LIKE(?)', "%#{search}%")
    else
      Article.all
    end
  end

end

app/models/error.rb
class Error < ApplicationRecord
  validates :erroe_message, presence: true
  validates :language, presence: true
  validates :status, presence: true
  validates :code, presence: true
  validates :cauce, presence: true
  belongs_to :user

  def self.search(search)
    if search != ""
      Error.where('erroe_message LIKE(?) OR status LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Error.all
    end
  end
end

app/models/resolution.rb
class Resolution < ApplicationRecord
  validates :status, presence: true
  belongs_to :user

  def self.search(search)
    if search != ''
      Resolution.where('status LIKE(?)', "%#{search}%")
    else
      Resolution.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :resolutions
  has_many :articles
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    if article.update(article_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:content).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def new
    @resolution = Resolution.new
  end

  def create
    @resolution = Resolution.new(resolution_params)
    if @resolution.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    resolution = Resolution.find(params[:id])
    resolution.destroy
    redirect_to root_path
  end

  def show
    @resolution = Resolution.find(params[:id])
  end

  def edit
    @resolution = Resolution.find(params[:id])
  end

  def update
    resolution = Resolution.find(params[:id])
    if resolution.update(resolution_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def resolution_params
    params.require(:resolution).permit(:status).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @resolutions = Resolution.includes(:user).order('created_at DESC').limit(10)
    @articles = Article.includes(:user).order('created_at DESC').limit(10)
  end

  def show
    @user = User.find(params[:id])
    @resolutions = @user.resolutions.order('created_at DESC')
    @articles = @user.articles.order('created_at DESC')
  end

  def search
    @resolutions = Resolution.search(params[:keyword])
    @articles = Article.search(params[:keyword])
  end

 

end

# user = User.find(params[:id])
# @nickname = user.nickname
# @resolutions = user.resolutions

app/helpers/application_helper.rb
module ApplicationHelper
 
  def qiita_markdown(markdown)
    processor = Qiita::Markdown::Processor.new(hostname: "example.com")
    processor.call(markdown)[:output].to_s.html_safe
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="more">
  <div class="detail">
    <ul class="more_list">
     <li>
      <%= link_to '詳細', article_path(article.id), method: :get %>
     </li>
      <% if user_signed_in? && current_user.id == article.user_id %>
      <li>
        <%= link_to '編集', edit_article_path(article.id), method: :get %>
      </li>
      <li>
        <%= link_to '削除', article_path(article.id), method: :delete %>
      </li>
      <% end %>
    </ul>
    <%= link_to "#{article.user.nickname}さん", "/users/#{article.user.id}"%>
    <div class="detail-top"> 
      <span style="color: white;">記事投稿</span>
    </div> 
    <div class="detail-bottom"> 
      <%= qiita_markdown(article.content) %>
    </div>
  </div> 
</div>
 

app/views/articles/_articleform.html.erb
<%= form_with(model: @article, local: true) do |form| %>   <div class="form-group">
    <div id='editor'>
      <textarea name="article[content]" id="n" class="form-control" rows="20" v-model='input' debounce='50'>
      </textarea>
      <div class="di_inline_t preview">
        <div v-html='input | marked'></div>
      </div>
    </div>
  </div>
  
  <div class="reslution-form">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

<script type="text/javascript">
 window.onload = function() {
 new Vue({
 el: '#editor',
 data: {
 input: '<%== j @article.content %>',
 },
 filters: {
 marked: marked,
 },
 });
 };
</script>

app/views/articles/edit.html.erb
<div class="contents row">
  <div class="container-error">
    <h3>記事フォーム</h3>
      <%= form_with(model: @article, local: true) do |form| %>   <div class="form-group">
    <div id='editor'>
      <textarea name="article[content]" id="n" class="form-control" rows="20" v-model='input' debounce='50'>
      </textarea>
      <div class="di_inline_t preview">
        <div v-html='input | marked'></div>
      </div>
    </div>
  </div>
  
  <div class="reslution-form">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

<script type="text/javascript">
 window.onload = function() {
 new Vue({
 el: '#editor',
 data: {
 input: '<%== j @article.content %>',
 },
 filters: {
 marked: marked,
 },
 });
 };
</script>
  </div>
</div>

app/views/articles/new.html.erb
<div class="contents row">
  <div class="container-error">
    <h3>記事フォーム</h3>
       <%= render partial: 'articleform' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="contents row">
  <div class="more">
    <div class="detail">
    <ul class="more_list">
      <li>
        <%= link_to '詳細', article_path(@article.id), method: :get %>
      </li>
        <% if user_signed_in? && current_user.id == @article.user_id %>
        <li>
          <%= link_to '編集', edit_article_path(@article.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', article_path(@article.id), method: :delete %>
        </li>
        <% end %>
        <%= link_to "#{@article.user.nickname}さん", "/users/#{@article.user.id}"%>
        <div class="detail-top"> 
          <span style="color: white;">記事投稿</span>
        </div> 
        <div class="detail-bottom"> 
          <%= qiita_markdown(@article.content) %>
        </div>
      </ul>
    </div> 
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Output</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Output</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
           <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <div class="grid-6">
              <%= link_to "エラー解決投稿", new_resolution_path, class: "post-1" %>
            </div>
             <div class="grid-6">
              <%= link_to "記事投稿", new_article_path, class: "post-1" %>
            </div>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        アウトプットをはじめよう
      </p>
    </footer>
  </body>
</html>

app/views/resolutions/_form.html.erb
 <%= form_with(model: @resolution, local: true,id: :editor) do |form| %>
   <div class="form-group">
    <div id='editor'>
      <textarea name="resolution[status]" id="n" class="form-control" rows="20" v-model='input' debounce='50'>
      エラーが起きた状況


      エラーメッセージ


      言語


      コードを記述


      原因・教訓


      </textarea>
      <div class="di_inline_t preview">
        <div v-html='input | marked'></div>
      </div>
    </div>
  </div>
  
  <div class="reslution-form">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

<script type="text/javascript">
 window.onload = function() {
 new Vue({
 el: '#editor',
 data: {
 input: '<%== j @resolution.status %>',
 },
 filters: {
 marked: marked,
 },
 });
 };
</script>

app/views/resolutions/_resolution.html.erb
<div class="more">
  <div class="detail">
  <ul class="more_list">
    <li>
      <%= link_to '詳細', resolution_path(resolution.id), method: :get %>
    </li>
      <% if user_signed_in? && current_user.id == resolution.user_id %>
      <li>
        <%= link_to '編集', edit_resolution_path(resolution.id), method: :get %>
      </li>
      <li>
        <%= link_to '削除', resolution_path(resolution.id), method: :delete %>
      </li>
      <% end %>
    </ul>
    <%= link_to "#{resolution.user.nickname}さん", "/users/#{resolution.user.id}"%>
    <div class="detail-top"> 
      <span style="color: white;">エラー解決の投稿</span>
    </div> 
    <div class="detail-bottom"> 
      <%= qiita_markdown(resolution.status) %>
    </div>
  </div> 
</div>

app/views/resolutions/edit.html.erb
<div class="contents row">
  <div class="container-error">
    <h3>エラー解決フォーム</h3>
    <%= form_with(model: @resolution, local: true,id: :editor) do |form| %>
   <div class="form-group">
    <div id='editor'>
      <textarea name="resolution[status]" id="n" class="form-control" rows="20" v-model='input' debounce='50'>
      </textarea>
      <div class="di_inline_t preview">
        <div v-html='input | marked'></div>
      </div>
    </div>
  </div>
  <div class="reslution-form">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

<script type="text/javascript">
 window.onload = function() {
 new Vue({
 el: '#editor',
 data: {
 input: '<%== j @resolution.status %>',
 },
 filters: {
 marked: marked,
 },
 });
 };
</script>
  </div>
</div>

app/views/resolutions/index.html.erb
<div class="form-image">
  <div class="title-contents">
      <p>
       <%= form_with(url: search_resolutions_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </P>
      <p class="service-explain-top">
        Let's
      </p>
      <p class="service-explain-bottom">
        Start the output
      </p>
  </div>
</div>
<div class="contents row">
    <% @resolutions.each do |resolution| %>
    <%= render partial: "resolution", locals: { resolution: resolution } %>
    <% end %>
</div>

app/views/resolutions/new.html.erb
<div class="contents row">
  <div class="container-error">
    <h3>エラー解決フォーム</h3>
       <%= render partial: 'form' %>
  </div>
</div>

app/views/resolutions/show.html.erb
<div class="contents row">
  <div class="more">
    <div class="detail">
    <ul class="more_list">
      <li>
        <%= link_to '詳細', resolution_path(@resolution.id), method: :get %>
      </li>
        <% if user_signed_in? && current_user.id == @resolution.user_id %>
        <li>
          <%= link_to '編集', edit_resolution_path(@resolution.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', resolution_path(@resolution.id), method: :delete %>
        </li>
        <% end %>
      </ul>
      <%= link_to "#{@resolution.user.nickname}さん", "/users/#{@resolution.user.id}"%>
      <div class="detail-top"> 
        <span style="color: white;">エラー解決の投稿</span>
      </div> 
      <div class="detail-bottom"> 
        <%= qiita_markdown(@resolution.status) %>
      </div>
    </div> 
  </div>
</div>
 

app/views/users/index.html.erb
 <div class="form-image">
  <div class="title-contents">
      <p>
       <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </P>
      <p class="service-explain-top">
        Let's
      </p>
      <p class="service-explain-bottom">
        Start the output
      </p>
  </div>
</div>
 <div class="user-show">
   <div class="contents row">
    <div class="title-name">エラー解決</div>
    <% @resolutions.each do |resolution| %>
    <%= render partial: "resolutions/resolution", locals: { resolution: resolution }%>
    <% end %>
  </div> 
  <div class="contents row">
     <div class="title-name">記事</div>
      <% @articles.each do |article| %> 
      <%= render partial: "articles/article", locals: { article: article } %> 
      <% end %>
  </div>
</div> 

app/views/users/search.html.erb
<div class="user-show">
  <div class="contents row">
    <div class="title-name">検索結果(エラー解決)</div>
      <% @resolutions.each do |resolution| %>
        <%= render partial: "resolutions/resolution", locals: { resolution: resolution } %>
      <% end %>
    </div>
   <div class="contents row">
    <div class="title-name">検索結果(記事)</div>
      <% @articles.each do |article| %>
        <%= render partial: "articles/article", locals: { article: article } %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
 <div class="user-show">
   <div class="contents row">
    <div class="title-name">エラー解決</div>
    <% @resolutions.each do |resolution| %>
    <%= render partial: "resolutions/resolution", locals: { resolution: resolution } %>
    <% end %>
  </div>
  <div class="contents row">
     <div class="title-name">記事</div>
      <% @articles.each do |article| %>
      <%= render partial: "articles/article", locals: { article: article } %>
      <% end %>
  </div>
</div>